# Generated by Django 3.1.3 on 2021-04-11 06:30

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.user_directory_path, verbose_name='Profile Picture'),
        ),
    ]
