# Generated by Django 3.2 on 2021-05-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_userprofile_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='service_request_no',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
