# Generated by Django 3.2 on 2021-05-08 14:08

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_servicerequest_service_request_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='background_pic',
            field=models.ImageField(default='default/bg_1.jpg', upload_to=app.models.user_directory_path, verbose_name='Background Picture'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(default='defualt/profile.png', upload_to=app.models.user_directory_path, verbose_name='Profile Picture'),
        ),
    ]
