# Generated by Django 3.2 on 2021-05-09 09:27

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_userprofile_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='slug',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(default='default/profile.png', upload_to=app.models.user_directory_path, verbose_name='Profile Picture'),
        ),
    ]
