# Generated by Django 3.2 on 2021-05-09 16:51

import app.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210509_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='background_pic',
            field=imagekit.models.fields.ProcessedImageField(default='default/bg_1.jpg', upload_to=app.models.user_directory_path, verbose_name='Background Picture'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=imagekit.models.fields.ProcessedImageField(default='default/profile.png', upload_to=app.models.user_directory_path, verbose_name='Profile Picture'),
        ),
    ]
