# Generated by Django 3.2 on 2021-05-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_servicerequest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='service_request_no',
            field=models.UUIDField(primary_key=True, serialize=False, unique=True),
        ),
    ]
