# Generated by Django 3.2 on 2021-05-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_servicerequest_service_request_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='service_request_no',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
