# Generated by Django 3.2 on 2021-05-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_servicerequest_service_request_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='service_request_no',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
