# Generated by Django 3.2 on 2021-05-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20210511_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='parts_charge',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
