# Generated by Django 3.2 on 2021-05-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20210511_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='parts_charge',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='service_charge',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
