# Generated by Django 3.2 on 2021-05-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20210513_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('p', 'Pending'), ('a', 'Approve')], default='pending', max_length=10),
        ),
    ]
