# Generated by Django 3.2 on 2021-05-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_servicerequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('p', 'Pending'), ('a', 'Approve')], default='p', max_length=10),
        ),
    ]
