# Generated by Django 3.2 on 2021-05-13 12:08

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_servicerequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='carousel/%y/%m/%d'),
        ),
    ]
